d5/tengo

objects/builtin_convert.go
runtime/vm_builtin_test.go

#7
objects/builtin_convert.go:
- Added defaults to all builtin convert functions except
bool as this one returns false for undefined, instead of undefined.
runtime/vm_builtin_test.go: 
- Added builtin bytes convert test
- Added tests for checking default value
behaviour for builtin convert funcs

Type conversion builtin take default values

---

compiler/stdlib/os.go

Hi! Since os.SEEK_SET, os,SEEK_CUR and os.SEEK_END is [deprecated](https://golang.org/pkg/os/#pkg-constants) i've changed that to io.SeekStart, io.SeekCurrent, and io.SeekEnd. Please check that

os: use SeekStart, SeekCurrent and SeekEnd instead deprecated values

---

objects/builtin_json.go
objects/builtins.go
objects/conversion.go
runtime/vm_builtin_test.go
script/conversion.go
script/script.go
script/variable.go

Fixes bug in script/conversion.go:interfaceToObject:
- Bug was caused by initialising var `arr` with length `len(v)`
- Followed by setting the `interfaceToObject(e)` in an append to `arr`
- This causes a slice for `len(v) = 3` as `[nil, nil, nil, 1, 2, 3,]`
Added conversion function ToMap:
- Takes an object and tries to make it a `map[string]interface{}`
Added conversion function ToSlice:
- Takes an object and tries to make it a `[]interface{}`
Added builtin function `to_json`:
- Takes an `array` or `map` as argument
- Returns value as `bytes`
Added builtin function `from_json`: 
- Takes a `bytes` or `string` as argument
- Returns value as `map`

Added builtin functions to_json and from_json

---

docs/interoperability.md
runtime/vm.go
script/compiled.go
script/compiled_test.go

This change is to allow replacing value of global variables after the script is compiled.

replacing values of the compiled script

---

docs/objects.md
docs/tutorial.md
objects/array.go
objects/bytes.go
objects/immautable_array.go
objects/string.go
objects/undefined.go
runtime/vm.go
runtime/vm_array_test.go
runtime/vm_bytes_test.go
runtime/vm_immutable_test.go
runtime/vm_string_test.go
runtime/vm_undefined_test.go

#83 
- IndexGet on sequence types: returns `undefined` if index is out of bounds
- IndexSet on Array: raises a run-time error if index is out of bounds
- IndexGet on Undefined type: always returns `undefined`
Slicing on sequence types: returns a new sequence of same type (except for ImmutableArray which returns Array) with the elements with:
- invalid slice index error if low > high
- sequence with elements within the range
- empty sequence when no element are within the range

IndexGet() of Array/ImmutableArray/Undefined types

---

compiler/compiler_for.go
runtime/vm_for_test.go

It wasn't fully documented, but, Tengo was supposed to support 'for' loops without condition expression:
```golang
for {
// infinite loop
}
```
This PR fixes a bug where VM incorrectly decremented the stack pointer for 'for' loop without conditions.

Fix a bug for 'for' loop without condition: "for {}"

---

compiler/opcodes.go
runtime/vm.go
runtime/vm_call_test.go
runtime/vm_module_test.go
runtime/vm_test.go

Stack trace for errors

---

compiler/compiler_test.go
compiler/parser/parser.go
script/script.go

Bailout shouldn't cause panic but return errors as in parser/parse_file.go

Fixed panic when bailout is triggered in parser.ParseFile()

---

compiler/compiler_test.go
compiler/parser/parser.go
compiler/parser/parser_map_test.go
runtime/vm_map_test.go

#114 
One comment:
p.expects allows only one token and I'm not sure whether token.Ident would be the best option, but I have left it as is for now.

String keys allowed for map definitions.

---

compiler/compiler_module.go
compiler/symbol_table.go
objects/builtins.go
objects/builtins_test.go
script/script_test.go
stdlib/stdlib.go
stdlib/stdlib_test.go

An example code:
```golang
// builtin functions
var builtinFunctions []*objects.BuiltinFunction
for _, bf := range objects.GetAllBuiltinFunctions() {
switch bf.Name {
case "print", "printf", "sprintf": // disabled
default:
builtinFunctions = append(builtinFunctions, bf)
}
}
s.SetBuiltinFunctions(builtinFunctions)
// builtin modules
builtinModules := stdlib.GetModules(stdlib.AllModuleNames()...)
delete(builtinModules, "os")
builtinModules["custom1"] = customModule
s.SetBuiltinModules(builtinModules)
```

add helper functions for builtin functions and builtin modules

---

objects/conversion.go
script/script.go
script/script_test.go

fixes #77 
I've the conversion in scripts.Add instead of objects.FromInterface as it is not clear that objects.FromInterface will never be called for builtins.

script.Add accepts a CallableFunc value

---

compiler/compiler.go
objects/builtin_convert.go
objects/builtin_json.go
objects/builtin_print.go
objects/bytes.go
objects/conversion.go
objects/errors.go
objects/string.go
runtime/vm_assignment_test.go
runtime/vm_builtin_test.go
stdlib/func_typedefs.go
stdlib/os.go
stdlib/os_exec.go
stdlib/os_file.go
stdlib/os_process.go
stdlib/os_test.go
stdlib/rand.go
stdlib/text.go
stdlib/text_regexp.go
stdlib/text_test.go
stdlib/times.go
tengo.go

`tengo.MaxStringLen` and `tengo.MaxBytesLen` is the maximum byte-length of string and bytes values respectively. This PR is to force those limits in various places. This is the first step for #112.

Limit the maximum size of string/bytes values

---

objects/callable_func.go
objects/conversion.go
runtime/vm_cond_test.go
runtime/vm_for_in_test.go
runtime/vm_for_test.go
runtime/vm_inc_dec_test.go
runtime/vm_module_test.go
runtime/vm_test.go

add module-import tests to most of runtime package

---

.goreleaser.yml
cmd/tengomin/main.go
compiler/compiler.go
docs/interoperability.md
runtime/vm.go
runtime/vm_assignment_test.go
runtime/vm_module_test.go
runtime/vm_test.go
script/script.go
script/script_module_test.go
script/script_test.go
stdlib/stdlib.go
stdlib/stdlib_test.go

stdlib is fully optional. this is in prep for #68

Decoupled stdlib from vm, script and compiler

---

runtime/vm.go

This is an alternative solution to cleanup the redundant binary operator code with no performance degradation. It also cleans up quite a bit of redundant v.fileSet.Position calls.

Removed redundant code in the VM with no performance loss.

---

docs/interoperability.md
script/compiled.go
script/script.go
script/script_concurrency_test.go

Use `Compiled.Clone()` to create a copy of Compiled instance. Cloned copies are safe for concurrent use by multiple goroutines.
```golang
// compile the script once
compiled, _ := myscript.Compile()
// execute from multiple goroutines
for i := 0; i < 100; i++ {
go func(compiled *script.Compiled) {
// inputs
_ = compiled.Set("a", rand.Intn(10))
_ = compiled.Set("b", rand.Intn(10))
_ = compiled.Set("c", rand.Intn(10))
if err := compiled.Run(); err != nil {
panic(err)
}
// outputs
d = compiled.Get("d").Int()
e = compiled.Get("e").Int()
}(compiled.Clone()) // Pass the cloned copy of Compiled
}
```
This resolves #133.

concurrent execution of script.Compiled

---

cli/cli.go
cli/cli_test.go
cmd/tengo/main.go
compiler/bytecode_decode.go
compiler/bytecode_test.go
compiler/compiler.go
docs/interoperability.md
objects/builtin_module.go
objects/importable.go
objects/module_map.go
objects/source_module.go
objects/user_function.go
runtime/vm_assignment_test.go
runtime/vm_test.go
script/script.go
script/script_concurrency_test.go
script/script_module_test.go
script/script_test.go
stdlib/builtin_modules.go
stdlib/gensrcmods.go
stdlib/source_modules.go
stdlib/stdlib.go
stdlib/stdlib_test.go

This PR is to fix an issue where decoded bytecode from binary has `nil` user functions. Bytecode decoder detects builtin modules (immutable maps with special field `__module_name__`) and replace them with known runtime builtin modules on the fly.

fix bytecode encoding/decoding of builtin modules

---

objects/undefined.go

I noticed that this seems to be a recurring pattern that can be easily avoided by allowing undefined to implement `Iterable`. As far as I can see, nothing is lost in the process while making the code cleaner.

Fixed runtime error when iterating over undefined.

---

objects/map.go
objects/map_test.go

Fixed the case where the a map element can be set with non-string key but can't be accessed with one.

Consistent Map set and get

---

stdlib/text.go
stdlib/text_test.go

String slicing with range doesn't work for variables that are expected to be string but turn out to not be strings (especially when retrieved from json). Substring function deals with such scenarios better than string conversion followed by slicing (works similar to other functions in the text library by first converting the object to string).

Substring function

---

stdlib/fmt.go
stdlib/fmt_test.go

fixes #143 
All Objects implement String(), so %v would work automatically if they're not converted to interface.

Fix %v formatting

---

compiler/ast/ident_list.go
compiler/ast/ident_list_test.go
compiler/compiler.go
compiler/compiler_test.go
compiler/opcodes.go
compiler/parser/parser.go
compiler/parser/parser_call_test.go
compiler/parser/parser_function_test.go
compiler/parser/parser_test.go
docs/tutorial.md
objects/compiled_function.go
runtime/vm.go
runtime/vm_function_test.go

This is just an initial implementation of variable-argument functions. I'm expecting to need to make changes, but I wanted to demonstrate the initial approach and get feedback before going further.
With this implementation, there are two types of functions supported: regular (`func(a,b,c) {}`) and variadic (`func(...args) {}`). Currently, if a function is variadic, it must have exactly one argument. The VM is responsible for consolidating passed parameters when it processes an `OpCall` instruction on a `CompiledFunction` or `Closure` that is variadic. It does this by consolidating the arguments on the stack into an array, which is then stored on the stack in place of the original first argument. If no arguments are passed to a variadic function call, an empty array is added to the stack …

variable-argument functions

---

compiler/compiler.go
compiler/compiler_optimize_test.go
compiler/compiler_scopes_test.go
compiler/compiler_spread_test.go
compiler/compiler_test.go
runtime/vm.go

The defer is no longer necessary. Although that said, it might be a good idea to name `OpSuspend` to something more relevant. Any ideas?

OpSuspend used to remove the defer from vm.run()

---

docs/objects.md

Replace the usages of `objects.ErrInvalidTypeConversion` in documentation as `ErrInvalidTypeConversion` was removed in https://github.com/d5/tengo/commit/3500c686b30e25be6629966e1a58421002c541ed.

replace outdated `ErrInvalidTypeConversion` in `docs/objects.md`

---

vm.go
vm_test.go

special errors returned from custom builtin modules can be identified easily by wrapping and using errors package's Is() and As() method.

update vm to raise wrapped runtime errors

---

vm.go

Removing slice allocation for callable arguments improves speed and allocation if arguments are provided to callable. Benchmark results are provided below. This makes sense for me because I run more than ten thousand of tengo scripts in a second. Let me know if benchmark is wrong or if I missed a point.
[Gist for bechmark](https://gist.github.com/ozanh/368c6383b4e5a90246a829e85217abd2)
Current
```
goos: linux
goarch: amd64
pkg: github.com/d5/tengo/v2
BenchmarkCallAlloc/NoArg        11966798                90.0 ns/op             8 B/op          1 allocs/op
BenchmarkCallAlloc/1Arg          8135835               148 ns/op              24 B/op          2 allocs/op
BenchmarkCallAlloc/2Arg          6741585               177 ns/op              40 B/op          2 allocs/op
```
After removing …

remove callable args alloc

---

examples/interoperability/main.go

Adding code examples to tengo will help people to easily adopt tengo so this interoperability example can be a start to add more examples.

add interoperability example

---

stdlib/json/encode.go
stdlib/json/json_test.go

Newly introduced stringEncode function fixes json module's unicode string encoding bug and closes #268 
This implementation interestingly looks faster than `strconv.AppendQuote()` for very small set of strings. Benchmark results are below
```
goos: linux
goarch: amd64
pkg: github.com/d5/tengo/v2/stdlib/json
BenchmarkStringEncodeASCII
BenchmarkStringEncodeASCII   	 5040517	       227 ns/op	     192 B/op
BenchmarkStringEncodeUnicode
BenchmarkStringEncodeUnicode 	 4289095	       283 ns/op	     192 B/op
BenchmarkQuoteASCII
BenchmarkQuoteASCII          	 4939057	       235 ns/op	     335 B/op
BenchmarkQuoteUnicode
BenchmarkQuoteUnicode        	 2456857	       480 ns/op	     543 B/op
```

fix stdlib json string encoding

---

compiler.go

There was a bug in the dead code elimination in Compiler: operands for the jump instructions that jump to the end of the function should be updated properly.
Fixes #283

fix a compiler bug with dead code optimization

---

cmd/tengo/main.go
compiler.go

Closes #281 by enabling child compiler to inherit file import allowance.
Also, a better way to compare bytes for shebang.

Fix nested file imports

---

compiler.go
vm_test.go

fix for in loop symbols

---

bytecode.go
vm_test.go

Fixes #289 
As @ozanh pointed out, this is a bug in Bytecode optimization code. While removing duplicate constants, some indexes were re-mapped 2+ times if duplicate CompiledFunctions exist.
@ozanh @geseq let me know what you guys think.

fix a bug in bytecode optimization code

---

compiler.go
compiler_test.go
docs/tengo-cli.md
docs/tutorial.md
objects.go
parser/expr.go
parser/opcodes.go
parser/parser.go
parser/parser_test.go
vm.go
vm_test.go

This PR is created in favor of feedback in #299 
- No new OpCode is introduced.
- OpCall has two operands now. Existing compiled scripts do not work, recompilation is required.
- OpCall second operand is used to denote whether last stack object is expanded/spread or not, which must be valid tengo Object `*Array, *ImmutableArray` or for custom user types `Spreader`.

spread last call argument v2

---

compiler.go
compiler_test.go
script.go
symbol_table.go
symbol_table_test.go
vm_test.go

Fixes #314.
This fixes a bug where an unassigned local variable is incorrectly referenced in 2 different scenarios:
```golang
(func() {
fn := fn()
})()
```
This should fail compilation with `unresolved reference` error because `fn` is not yet defined.
```golang
fn := func() {}	
(func() {
fn := fn()
return fn
})()
```
This should compile and run correctly. `fn` oh the left-hand side is a new local variable and `fn` on the right-hand side is a global variable defined outside the function.

fix local symbol resolution bug

---

.github/workflows/test.yml

This fixes `set-env` and `add-path`
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

fix GitHub Actions set-env and add-path

---

.github/workflows/test.yml
builtins.go
builtins_test.go
errors.go

add builtin range function:   
range(start, stop[, step])   
usage examples: 
range(0,0) ----> []   
range(0, 5) -----> [0, 1, 2, 3, 4]   
range(0, 10, 3) -----> [0, 3, 6, 9]
range(0, -10, 2) -----> [0, -2, -4, -6, -8]
special:
The step must be greater than 0 to prevent infinite loops

PR: builtin range function #326

---

vm.go

This optimization perhaps is premature but I think it's a small easy win to just allocate the map precisely with the target number of elements since they are known from the bytecode operand.

For the OpMap VM instruction, since numElements is known just use the capacity hint.

---

compiler.go
docs/interoperability.md
modules.go
script.go

Fixes #348.
Passes `make test`.

Extract ModuleGetter interface for dynamic imports

---

script.go

As described in issue #344. I've added a defer statement to handle panics.

Handle panics by deferring recover as an error

---

compiler.go
compiler_test.go
docs/tutorial.md
tengo.go
testdata/issue286/dos/cinco/cinco.mshk
testdata/issue286/dos/dos.mshk
testdata/issue286/dos/quatro/quatro.mshk
testdata/issue286/test.mshk
testdata/issue286/tres.tengo
testdata/issue286/uno.mshk

This PR features issue #286 by implementing `tengo.Compiler.SetImportFileExt()` method which allows specifying custom extension names.
This feature aims for "`tengo`" as a library usage and should not affect the "/cmd/tengo" itself.
```diff
func main(){
...
c := tengo.NewCompiler(srcFile, nil, nil, modules, nil)
c.EnableFileImport(true)
c.SetImportDir(filepath.Dir(pathFileSource))
+	err := c.SetImportFileExt(".tengo", ".mshk") // It will search *.tengo and *.mshk script files
...
}
```
- Related issue
- #286
- #332
---
- EDIT: Previously, in the first commit, `c.SetImportExt(".mshk")` searched for both `*.tengo` and `*.mshk` (`*.tengo` by default) with no input validation. <br>But currently it needs to explicitly define as `c.SetImportFileExt(".tengo", ".mshk")` for both file extensions. …

add custom extension support for importing source file

---

compiler.go
compiler_test.go

fixes #376
essentially we need to check and ignore the jump positions before we mark a return for elimination

fix deadcode optimization

---

.github/workflows/release.yml

another one @d5. 
we have two options to fix releases, either increase compatibility to go 1.16+ or use newer goreleaser. more details here: https://github.com/goreleaser/goreleaser/pull/2069

update goreleaser to fix releases

---

.github/workflows/release.yml

@d5 turns out the changes that fixed this got reverted in a later refactor. the most straightforward way to fix is to restrict to go 1.16+

Fix go releases

---

parser/parser.go
parser/parser_test.go
parser/scanner.go

Fix parsing oct and hex numbers

---

compiler.go
compiler_test.go

fixes #386 
I'm not sure this is the best solution to the problem, but it's fairly minimal. I can't really think of anything other than functions that might need this recursive definition.
@d5 thoughts?

fix runtime panics on self assignment

---

compiler.go
compiler_test.go
script_test.go

I have posted an issue explaining this https://github.com/d5/tengo/issues/390

fix: do not invert token.Less to token.Greater in compiler

---

script_test.go
vm.go

It seems that SourceMap should be copied to the new CompiledFunction when executing OpClosure. All other fields are copied but this field is left out.
I've added a test to explain

fix: copy SourceMap in vm OpClosure branch

---

script.go
script_test.go

Use Object.Copy when cloning globals in Compiled

---

vm.go
vm_test.go

Variables `low` and `high` are being shadowed. Therefore, when slice index is invalid (not an `integer`), the error message does not gives *correct* invalid type hint, and always return `Runtime Error: invalid slice index type: int`

fix slice low/high index shadowing variables in vm

---

script.go

Allow multiple Go routines to concurrently `Clone()` a `Compiled` script.

Downgrade exclusive lock to shared lock when cloning a script

---

docs/objects.md

Get example code to working state for StringArray object injection Just calling "print()" produces no output. Importing fmt and calling println() works. The output was also producing "one, twothree" instead of "one, two, three" as noted in the comment. This example code seems to have diverged from the implementation current at the time that it was written. This code now builds, executes, and produces the expected output for me.

Update objects.md to fix StringArray object injection example

---

stdlib/json/decode.go
stdlib/json/json_test.go
stdlib/json_test.go

Fixes #379 
slightly modify json.decode to solve precision problem when decode bigint in json

fix: solve precision problem when decode bigint in json

---

docs/stdlib-json.md

Run the json module example in the Tengo playgroud giving the following error:
```
Runtime Error: wrong number of arguments in call to 'user-function:encode'
at (main):7:13
------------------------
Version: 2.12.0
```
This PR fixes the json.indent docs.

fix json.indent docs

---

vm.go
vm_test.go

Add a missing switch case corresponding to a slice of an unsupported type. Without it Tengo continues execution past the unsupported slice with an invalid stack state, causing unexpected behaviour or obscure errors.
Example:
```golang
test := func() {
a := 42
return undefined[:5]
}
fmt := import("fmt")
fmt.println(test())  // -> prints 42
```
This PR changes it to throw a runtime error instead, which is consistent with similar cases such as using a function call operator on an unsupported type.

Throw a runtime error when trying to slice an unsupported type

---

vm.go
vm_test.go

> This is a follow-up to https://github.com/d5/tengo/pull/442
Add a missing `return` to actually stop script execution after detecting an invalid slice operation. Otherwise the execution continues with an invalid stack causing unexpected behaviour:
```golang
a := 123[-1:2]
a += 1  // runtime error: index out of range [-1]
```

Fix: stop execution when trying to slice an unsupported type
