d5/tengo

README.md
=> Add Starlark benchmark result

README.md, compiler/opcodes.go, runtime/vm.go, script/compiled.go, script/compiled_test.go, script/script.go
=> Add Context to script run

compiler/compiler_assign.go, objects/array.go, objects/bytes.go, objects/errors.go, objects/immutable_map.go, objects/index_assignable.go, objects/indexable.go, objects/map.go, objects/string.go, runtime/vm.go, runtime/vm_indexable_test.go, runtime/vm_module_test.go, runtime/vm_test.go
=> Indexable and IndexAssignable

objects/array.go, objects/array_iterator.go, objects/immutable_map.go, objects/immutable_map_iterator.go, objects/iterable.go, objects/map.go, objects/map_iterator.go, objects/string.go, objects/string_iterator.go, runtime/vm.go, runtime/vm_iterable_test.go
=> Iterable interface

README.md, docs/README.md, docs/builtins.md, docs/interoperability.md, docs/objects.md, docs/runtime-types.md, docs/stdlib-exec.md, docs/stdlib-math.md, docs/stdlib-os.md, docs/stdlib.md, docs/tengo-cli.md, docs/tutorial.md
=> Documentation directory (/docs)

README.md
=> add goja to benchmark

docs/interoperability.md, script/script.go, script/script_test.go
=> sandbox environment for scripts

compiler/compiler_test.go, docs/builtins.md, objects/builtin_print.go, objects/builtins.go, runtime/vm_builtin_test.go
=> add 'printf' and 'sprintf' builtin functions

docs/builtins.md
=> add 'to_json' and 'from_json' to builtin documentation

README.md, docs/interoperability.md, docs/objects.md, docs/tutorial.md, runtime/vm_call_test.go, runtime/vm_indexable_test.go, script/script.go, script/script_module_test.go
=> Script Imports

compiler/parser/parser.go, compiler/parser/sync.go, compiler/scanner/scanner_test.go, compiler/token/tokens.go
=> Remove unused tokens

README.md, docs/builtins.md, docs/objects.md, docs/operators.md, docs/tutorial.md, objects/char.go, objects/int.go, runtime/vm_char_test.go, runtime/vm_integer_test.go
=> Operators on Char type

compiler/stdlib/func_typedefs.go, compiler/stdlib/func_typedefs_test.go, compiler/stdlib/rand.go, compiler/stdlib/rand_test.go, compiler/stdlib/stdlib.go, compiler/stdlib/stdlib_test.go, docs/stdlib-rand.md, docs/stdlib.md
=> add 'rand' module

cmd/bench/main.go, cmd/tengo/main.go, compiler/compiler.go, compiler/compiler_test.go, runtime/vm_test.go, script/script.go
=> Fixes a REPL bug (Issue #91)

compiler/bytecode.go, compiler/compiler_test.go, runtime/vm_test.go
=> Bytecode formatting

cmd/tengo/main.go, compiler/compiler_error_report_test.go, compiler/error.go, compiler/parser/error.go, compiler/parser/error_list_test.go, compiler/parser/error_test.go, runtime/vm.go, runtime/vm_call_test.go, runtime/vm_error_report_test.go, runtime/vm_module_test.go
Fixed #109 and cleaned up the code a little.
=> Runtime error trace format

cmd/bench/main.go, cmd/tengo/main.go, docs/interoperability.md, objects/builtins.go, runtime/vm.go, runtime/vm_test.go, script/script.go, script/script_module_test.go, script/script_test.go
@d5 I still need to review all the changes but the feature is working.  Please review as well.
#119
=> SetBuiltinFunctions and SetBuiltinModules

docs/objects.md, docs/tutorial.md, runtime/vm_assignment_test.go, runtime/vm_module_test.go
1. composite types -> compound types
2. composite assignment -> compound assignment
=> minor doc update

compiler/compiler_test.go, docs/builtins.md, objects/builtin_print.go, objects/builtins.go, script/script_test.go
=> Added println

compiler/bytecode.go, compiler/bytecode_decode.go, compiler/bytecode_optimize.go, compiler/bytecode_test.go, compiler/compiler.go, compiler/compiler_test.go
=> fix bytecode encoding/decoding

compiler/compiler.go, compiler/compiler_module.go, compiler/instructions.go, runtime/vm_function_test.go, runtime/vm_if_test.go, runtime/vm_module_test.go, script/compiled_test.go
=> bug fix for function return and if statement

compiler/compilation_scope.go, compiler/compiler.go, compiler/compiler_module.go, compiler/compiler_optimize_test.go, compiler/compiler_scopes_test.go, compiler/compiler_test.go, compiler/symbol_table.go, compiler/symbol_table_test.go, runtime/vm_scopes_test.go
=> Compiler optimization first iteration

compiler/compiler.go, runtime/vm_if_test.go
=> fix a bug in dead code elimination

runtime/vm.go, runtime/vm_test.go
=> fix script timeout bug

docs/stdlib-json.md, stdlib/json.go, stdlib/json/decode.go, stdlib/json/encode.go, stdlib/json/json_test.go, stdlib/json/scanner.go, stdlib/json_test.go
=> json module faster implementation

assert/assert.go, compiler/instructions.go, compiler/symbol_scopes.go, objects/bytes.go, objects/conversion.go, objects/object_test.go, runtime/vm.go, script/script.go, stdlib/fmt.go, stdlib/times_test.go
based on https://golangci.com/r/github.com/d5/tengo
=> minor lint fixes

objects/builtin_format.go, objects/builtins.go, objects/formatter.go, runtime/vm_builtin_test.go, stdlib/fmt.go
=> Custom formatter based on go's fmt package.

docs/tutorial.md
=> update syntax documentation

runtime/vm.go, runtime/vm_function_test.go
=> Fixed missing ObjectPtr check in OpSetSelLocal

docs/stdlib-base64.md, docs/stdlib-hex.md, docs/stdlib.md, stdlib/base64.go, stdlib/base64_test.go, stdlib/builtin_modules.go, stdlib/func_typedefs.go, stdlib/hex.go, stdlib/hex_test.go
=> Stdlib encodings: hex, base64 (#216)

stdlib/os_file.go
=> Spell correction

vm.go
=> Revert "remove callable args alloc"

cmd/tengo/main.go, docs/tengo-cli.md
This PR should add a simple Shebang support for Tengo scripts and closes #251
=> add shebang support

compiler_test.go, symbol_table.go, vm_test.go
=> fix issues with symbols in global scope blocks

README.md
Add link to vim syntax highlighting package for tengo
=> vim syntax highlighter

.github/workflows/test.yml
Note: golint is unmaintained, so should probably be replaced, but for now fixing the error to allow testing other PRs
=> fix golint

stdlib/fmt.go
This pull request resolves issue https://github.com/d5/tengo/issues/352 and additionally adds a minimum args check.
=> fix: divergence from std go and minimal args check

parser/parser.go, parser/parser_test.go, vm_test.go
Change-Id: Iba1ad456d5b020375bb0416f44fb54bc2e346d62
=> bugfix: parse expect error when mis match braces

docs/tutorial.md
=> tutorial: use any instead of interface{}
